[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"
evm_version = "shanghai"

[fmt]
line_length = 100

[etherscan]
tanenbaum = { url = "https://explorer.tanenbaum.io/api", key = "blockscout" }
mainnet = { url = "https://explorer.syscoin.org/api", key = "blockscout" }
local = { url = "http://localhost:4000/api", key = "blockscout" }


[rpc_endpoints]
tanenbaum = "https://rpc.tanenbaum.io"
mainnet = "https://rpc.syscoin.org"
local = "http://localhost:8545"
